* What is homepage-cljs?
  
  This is a simple starting project I made use to learn Clojurescript and React.
  The main concept is to have a homepage where I can store and access
  easily all my bookmarks, browse quickly some subreddit, read rss
  feeds, and add more functionality down the road when I found
  something that could be useful to have in a homepage.
  
  Homepage-cljs can optionally store the user's data on the cloud
  (temporary on a sub-domain of my website), so the user can access to
  its homepage between different computers and devices (I'm already
  working on a mobile client for it called homepage-native with
  Clojurescript and React native).
  
  The project started as a personal one, but then I decided to let it
  available to everyone here on GitHub so anyone can give me feedback
  about it or simply enjoy it.
  
  
  



* Development mode

To start the Figwheel compiler, navigate to the project folder and run the following command in the terminal:

~lein figwheel~

Figwheel will automatically push cljs changes to the browser.
Once Figwheel starts up, you should be able to open the `public/index.html` page in the browser.

* REPL

The project is setup to start nREPL on port `7002` once Figwheel starts.
Once you connect to the nREPL, run `(cljs)` to switch to the ClojureScript REPL.

* Building for production

```
lein clean
lein package
```
